name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
          python-version: [3.8, "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Build with Makefile
        run: make
